export const METRIC_NAMES = {
  FCP: 'FCP',
  TTFB: 'TTFB',
  DOM_LOAD: 'DOM_LOAD',
  WINDOW_LOAD: 'WINDOW_LOAD',
  RESOURCE: 'RESOURCE',
};

export const MAX_RETRY_COUNT_ON_NETWORK_FAULT = 5;
export const REQUEST_RETRY_DELAY_TIME = 3000;
